name: nasa_now
description: "Prototype"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


python_ffi:
  modules:
    basic_cli_adder:
      path: python-modules/basic_cli_adder.py

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  http: ^1.0.0

  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  path_provider: ^2.0.2
  provider: ^6.0.0
  intl: ^0.19.0
  full_screen_image: ^2.0.0
  geolocator: ^8.0.0
  flutter_js: ^0.8.0
  csv: ^6.0.0
  geocoding: ^3.0.0
  geojson_vi: ^2.2.3
  country_coder: ^1.2.0
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

  fonts:
    - family: Megatrans
      fonts:
        - asset: fonts/MegatransdemoRegular-8M9B0.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages